#pragma once

enum eBodyPart : __int32 {
	BODYPART_NONE = 0,
	BODYPART_TORSO = 1,
	BODYPART_HEAD = 2,
	BODYPART_LEFT_UPPER_ARM = 3,
	BODYPART_RIGHT_UPPER_ARM = 4,
	BODYPART_LEFT_HAND = 5,
	BODYPART_RIGHT_HAND = 6,
	BODYPART_LEFT_LEG = 7,
	BODYPART_RIGHT_LEG = 8,
	BODYPART_LEFT_FOOT = 9,
	BODYPART_RIGHT_FOOT = 10,
	BODYPART_LOWER_RIGHT_LEG = 11,
};

enum eBodyParts : unsigned int {
	LOWER_LEG_L,
	TORSO,
	HEAD,
	UPPER_ARM_L,
	UPPER_ARM_R,
	HAND_L,
	HAND_R,
	UPPER_LEG_L,
	UPPER_LEG_R,
	FOOT_L,
	FOOT_R,
	LOWER_LEG_R
};
